# Generated by Django 3.2.9 on 2022-06-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimilarProduct',
        ),
    ]
